### ISSUE TITLE
1.20.1 Support for Controlling

### ISSUE THREAD

**Issue by Gamemassa** [Siphalor/nmuk#20] opened 2023-08-02 23:04 UTC
Hi, I noticed that NMUK for Fabric 1.20.1 was updated today. Did you guys happen to add support for Controlling? I had messaged in a previous post (https://github.com/Siphalor/amecs/issues/108) that I had reached out to [jaredlll08](https://github.com/jaredlll08/Controlling) and he said he's add api-related stuff to his mod if that'd make it easier for you guys to add support on your end (and I'm sure he'd still be happy to do that).

**Comment by Gamemassa** [comment] 2023-08-07 13:57
@Siphalor

**Comment by Gamemassa** [comment] 2023-08-19 20:53
@Siphalor @Klotzi111 Bumping this thread.

**Comment by Siphalor** [comment] 2023-08-20 01:00
Hi, I understand that Controlling support is a big pain point right now, but bumping threads won't really speed things up ;)

I'm still having thoughts about how NMUK and Amecs could provide/make use of a more generalized, so I don't have to hard-code compatibility for Controlling into these mods. Especially since both NMUK and Amecs can be used as libraries themselves.

The big issue is that Controlling is overwriting a lot of the vanilla logic by (mostly) copy-pasting Vanilla code into its implementation.
Therefore, the mixins of NMUK and Amecs won't work. 
As far as I know, Klotzi implemented Controlling support by basically duplicating and adjusting the GUI mixins for Controlling.
I'm generally not a fan of mixin into logic of third-party mods.

I had a look at the 1.20 APIs of Controlling and Amecs support might be possible with these new APIs.
NMUK support would still require a lot of special handling and mixins.

I also don't really like that using the new Controlling APIs would be limited to Minecraft 1.20 and up, as Controlling seems to be developed mostly on the latest Minecraft versions.
Amecs and NMUK on the other hand offer a wide range of version support, so having Controlling support for 1.20+ would probably leave out a lot of the user base.

I might reach out to Jared myself in the future to see if they have any other thoughts on this topic.

I'm going to close this issue as this is just a duplicate of Siphalor/amecs#108.
Please refrain from posting these regular bumps as they aren't really productive, and otherwise I'm going to see myself forced to lock the discussions, as it has already happened with the Amecs issue.

**Closed as not planned by Siphalor** 2023-08-20 01:00 UTC

**Comment by Gamemassa** [comment] 2023-08-20 04:04
I'm sorry. I wasn't trying to "speed things up" so much as I was just hoping for any kind of response. I posted in Siphalor/amecs#108 over a month ago and hadn't heard anything, so I just wasn't sure if you saw my post.

I understand that mod updates can be very slow and time-consuming, so I would never try to rush developers. It's just frustrating when I post something and nobody responds.
