### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by warior456** [Siphalor/nmuk#16] opened 2023-01-28 18:42 UTC
the game crashes with this mod installed removing it fixes it, removing dynamic fps doesnt fix
[crash-2023-01-16_13.03.47-client.txt](https://github.com/Siphalor/nmuk/files/10527996/crash-2023-01-16_13.03.47-client.txt)
[crash-2023-01-28_19.27.47-client.txt](https://github.com/Siphalor/nmuk/files/10527997/crash-2023-01-28_19.27.47-client.txt)
[crash-2023-01-28_19.29.12-client.txt](https://github.com/Siphalor/nmuk/files/10527998/crash-2023-01-28_19.29.12-client.txt)
[crash-2023-01-28_19.30.02-client.txt](https://github.com/Siphalor/nmuk/files/10527999/crash-2023-01-28_19.30.02-client.txt)
[crash-2023-01-28_19.30.44-client.txt](https://github.com/Siphalor/nmuk/files/10528000/crash-2023-01-28_19.30.44-client.txt)
[crash-2023-01-28_19.32.07-client.txt](https://github.com/Siphalor/nmuk/files/10528001/crash-2023-01-28_19.32.07-client.txt)
[crash-2023-01-28_19.33.23-client.txt](https://github.com/Siphalor/nmuk/files/10528002/crash-2023-01-28_19.33.23-client.txt)
[crash-2023-01-28_19.36.50-client.txt](https://github.com/Siphalor/nmuk/files/10528003/crash-2023-01-28_19.36.50-client.txt)
[crash-2023-01-28_19.38.27-client.txt](https://github.com/Siphalor/nmuk/files/10528004/crash-2023-01-28_19.38.27-client.txt)
[crash-2023-01-28_19.41.31-client.txt](https://github.com/Siphalor/nmuk/files/10528005/crash-2023-01-28_19.41.31-client.txt)

**Comment by Siphalor** [comment] 2023-01-29 21:29
Duplicate of #15

**Closed as completed by Siphalor** 2023-01-29 21:29 UTC
